In [1]:
import h5py

In [2]:
FILE_NAME = "./data/yeouido/visual_feature_map/1.0.0/15/24022/13903.h5"

ROOT_OBJ_DIR = "./data/yeouido/visual_feature_map/1.0.0/15/"

In [3]:
with h5py.File(FILE_NAME, "r") as f: 
    print(f.keys())
    print(f.get("points"))
    print(type(f.get("points")[:]))
    print(f.get("points")[:])


<KeysViewHDF5 ['desc', 'points', 'pose', 'rpy']>
<HDF5 dataset "points": shape (95, 3), type "<f8">
<class 'numpy.ndarray'>
[[  -98.61736004 -1457.44978516     9.03233797]
 [  -92.89063854 -1453.79866807     5.56315057]
 [  -94.75960885 -1453.48623598     7.07370586]
 [  -99.83589322 -1457.75400736     7.1557276 ]
 [ -100.76906693 -1457.83772212     8.50371636]
 [  -94.19624649 -1453.4037895      6.5434407 ]
 [ -100.81033388 -1457.75365018     5.61031217]
 [  -92.82444191 -1453.90512985     8.50506795]
 [  -99.93463087 -1457.56860844     8.29453841]
 [ -101.9939806  -1458.57396976     8.06127197]
 [ -101.83602679 -1458.39988008     6.83050605]
 [ -102.87785499 -1458.91873053     8.38081952]
 [ -102.65793186 -1459.20695253     7.04637453]
 [ -103.69784933 -1460.05415158     6.72581908]
 [ -101.15801772 -1458.19057369     8.15127497]
 [  -97.06949242 -1455.39485314     8.21709314]
 [ -104.44961817 -1460.29430036     8.0681852 ]
 [ -103.57108208 -1460.15933519     7.71603311]
 [  -95.0981

In [4]:
from pathlib import Path

from numpy import ndarray


def get_points_from_dataset(file_name: Path) -> ndarray:
    with h5py.File(file_name, "r+") as f:
        data = f.get("points")[:]
        return data 

In [5]:
get_points_from_dataset(FILE_NAME)

array([[  -98.61736004, -1457.44978516,     9.03233797],
       [  -92.89063854, -1453.79866807,     5.56315057],
       [  -94.75960885, -1453.48623598,     7.07370586],
       [  -99.83589322, -1457.75400736,     7.1557276 ],
       [ -100.76906693, -1457.83772212,     8.50371636],
       [  -94.19624649, -1453.4037895 ,     6.5434407 ],
       [ -100.81033388, -1457.75365018,     5.61031217],
       [  -92.82444191, -1453.90512985,     8.50506795],
       [  -99.93463087, -1457.56860844,     8.29453841],
       [ -101.9939806 , -1458.57396976,     8.06127197],
       [ -101.83602679, -1458.39988008,     6.83050605],
       [ -102.87785499, -1458.91873053,     8.38081952],
       [ -102.65793186, -1459.20695253,     7.04637453],
       [ -103.69784933, -1460.05415158,     6.72581908],
       [ -101.15801772, -1458.19057369,     8.15127497],
       [  -97.06949242, -1455.39485314,     8.21709314],
       [ -104.44961817, -1460.29430036,     8.0681852 ],
       [ -103.57108208, -1460.1

In [6]:
from typing import List
import os


def get_subdir_paths(dir_name: Path) -> List[Path]:
    subdir_names = os.listdir(dir_name)
    subdir_paths = list(map(lambda x: os.path.join(dir_name, x), subdir_names))
    return subdir_paths


In [7]:
get_subdir_paths(ROOT_OBJ_DIR)

['./data/yeouido/visual_feature_map/1.0.0/15/24062',
 './data/yeouido/visual_feature_map/1.0.0/15/24096',
 './data/yeouido/visual_feature_map/1.0.0/15/24091',
 './data/yeouido/visual_feature_map/1.0.0/15/24065',
 './data/yeouido/visual_feature_map/1.0.0/15/24098',
 './data/yeouido/visual_feature_map/1.0.0/15/24053',
 './data/yeouido/visual_feature_map/1.0.0/15/24054',
 './data/yeouido/visual_feature_map/1.0.0/15/24038',
 './data/yeouido/visual_feature_map/1.0.0/15/24031',
 './data/yeouido/visual_feature_map/1.0.0/15/24036',
 './data/yeouido/visual_feature_map/1.0.0/15/24055',
 './data/yeouido/visual_feature_map/1.0.0/15/24099',
 './data/yeouido/visual_feature_map/1.0.0/15/24052',
 './data/yeouido/visual_feature_map/1.0.0/15/24064',
 './data/yeouido/visual_feature_map/1.0.0/15/24090',
 './data/yeouido/visual_feature_map/1.0.0/15/24097',
 './data/yeouido/visual_feature_map/1.0.0/15/24063',
 './data/yeouido/visual_feature_map/1.0.0/15/24037',
 './data/yeouido/visual_feature_map/1.0.0/15/2

In [8]:
get_subdir_paths('./data/yeouido/visual_feature_map/1.0.0/15/24026')

['./data/yeouido/visual_feature_map/1.0.0/15/24026/13907.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24026/13906.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24026/13909.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24026/13908.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24026/13904.h5']

In [9]:
from functools import reduce
from operator import iconcat


def get_dataset_paths(base_obj_dir: Path) -> List[Path]:
    obj_paths = get_subdir_paths(base_obj_dir)
    dataset_pathss = list(map(lambda x: get_subdir_paths(x), obj_paths))
    dataset_paths = list(reduce(iconcat, dataset_pathss, []))
    return dataset_paths


In [10]:
get_dataset_paths(ROOT_OBJ_DIR)

['./data/yeouido/visual_feature_map/1.0.0/15/24062/13894.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24062/13867.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24062/13946.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24062/13890.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24062/13863.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24062/13923.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24062/13873.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24062/13907.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24062/13956.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24062/13947.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24062/13891.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24062/13922.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24062/13872.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24062/13957.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24062/13895.h5',
 './data/yeouido/visual_feature_map/1.0.0/15/24062/13866.h5',
 './data

In [19]:
from numpy import concatenate
import numpy as np


def get_points(root_obj_dir: Path) -> ndarray:
    dataset_paths = get_dataset_paths(root_obj_dir)
    pointss = list(map(lambda x: get_points_from_dataset(x), dataset_paths))
    pointss = list(map(np.ndarray.tolist, pointss))
    points = list(reduce(iconcat, pointss, []))
    return points

In [21]:
points = get_points(ROOT_OBJ_DIR)

In [22]:
len(points)

898592

In [23]:
np_points = np.array(points)
np_points

array([[ -864.94744759, -1124.73718231,    11.90626854],
       [ -865.08942008, -1123.22325622,    11.8896675 ],
       [ -864.06443319, -1123.51043818,    11.90174805],
       ...,
       [  -96.73895303, -1314.54992442,     2.19323736],
       [  -97.38822706, -1313.40492367,     2.20702424],
       [ -153.11441068, -1396.05500243,    12.07730773]])

In [24]:
np_points.shape

(898592, 3)

In [37]:
# import matplotlib.pyplot as plt

# xs = np_points[:, 0].tolist()
# ys = np_points[:, 1].tolist()
# zs = np_points[:, 2].tolist()


# fig = plt.figure(figsize=(16,10), dpi=300)
# ax = plt.axes(projection='3d')
# ax.scatter(xs, ys, zs, cmap='binary')

In [39]:
import pyvista as pv

pdata = pv.PolyData(np_points)
pdata.plot(full_screen=True)

Widget(value="<iframe src='http://localhost:61625/index.html?ui=P_0x2bdcac650_1&reconnect=auto' style='width: …