In [2]:
from pyvista import OpenFOAMReader


# FILE_PATH = "./data/results/windAroundBuildingsOld/open.foam"
FILE_PATH = "/home/ubuntu/openfoam/OpenFOAM/openfoam-v2212/run/testCase/open.foam"


reader = OpenFOAMReader(FILE_PATH)

In [3]:
print(f"All patch names: {reader.patch_array_names}")
print(f"All patch status: {reader.all_patch_arrays_status}")

All patch names: ['internalMesh', 'patch/inlet', 'patch/outlet', 'patch/ground', 'patch/object', 'patch/fixedWalls']
All patch status: {'internalMesh': True, 'patch/inlet': True, 'patch/outlet': True, 'patch/ground': True, 'patch/object': True, 'patch/fixedWalls': True}


In [4]:
mesh = reader.read()
internal_mesh = mesh["internalMesh"]  # or internal_mesh = mesh[0]

2023-06-19 15:32:49.132 ( 128.856s) [        B3AB4000]  vtkOpenFOAMReader.cxx:8653   ERR| vtkOpenFOAMReaderPrivate (0x3b90d10): Error reading line 28 of /home/ubuntu/openfoam/OpenFOAM/openfoam-v2212/run/testCase/0/U: Expected number, string or ( for uniform entry, found Uinlet
ERROR:root:Error reading line 28 of /home/ubuntu/openfoam/OpenFOAM/openfoam-v2212/run/testCase/0/U: Expected number, string or ( for uniform entry, found Uinlet
ERROR:root:Error reading line 21 of /home/ubuntu/openfoam/OpenFOAM/openfoam-v2212/run/testCase/0/epsilon: Expected number, string or ( for uniform entry, found epsilonInlet
2023-06-19 15:32:49.133 ( 128.857s) [        B3AB4000]  vtkOpenFOAMReader.cxx:8653   ERR| vtkOpenFOAMReaderPrivate (0x3b90d10): Error reading line 21 of /home/ubuntu/openfoam/OpenFOAM/openfoam-v2212/run/testCase/0/epsilon: Expected number, string or ( for uniform entry, found epsilonInlet
ERROR:root:Error reading line 21 of /home/ubuntu/openfoam/OpenFOAM/openfoam-v2212/run/testCase/0/k

In [5]:
print(f"Mesh patches: {mesh.keys()}")

Mesh patches: ['internalMesh', 'boundary']


In [6]:
print(internal_mesh)

UnstructuredGrid (0x7fc0dad50f40)
  N Cells:    62188
  N Points:   77648
  X Bounds:   -1.500e+00, 1.500e+00
  Y Bounds:   1.000e-02, 3.000e+00
  Z Bounds:   -1.500e+00, 1.500e+00
  N Arrays:   0


In [7]:
print(internal_mesh.cell_data)
print(internal_mesh.point_data)
print(f"Available Time Values: {reader.time_values}")
reader.set_active_time_value(50)
mesh = reader.read()
internal_mesh = mesh["internalMesh"]

pyvista DataSetAttributes
Association     : CELL
Active Scalars  : None
Active Vectors  : None
Active Texture  : None
Active Normals  : None
Contains arrays : None
pyvista DataSetAttributes
Association     : POINT
Active Scalars  : None
Active Vectors  : None
Active Texture  : None
Active Normals  : None
Contains arrays : None
Available Time Values: [0.0, 50.0, 73.0]


In [8]:
# mesh.plot()

In [9]:
type(mesh)

pyvista.core.composite.MultiBlock

In [10]:
type(reader.time_values[0])

float

In [11]:
type(reader)

pyvista.utilities.reader.OpenFOAMReader

In [12]:
type(internal_mesh)

pyvista.core.pointset.UnstructuredGrid

In [13]:
internal_mesh._get_attrs()

[('N Cells', 62188, '{}'),
 ('N Points', 77648, '{}'),
 ('X Bounds', (-1.5, 1.5), '{:.3e}, {:.3e}'),
 ('Y Bounds', (0.009999999776482582, 3.0), '{:.3e}, {:.3e}'),
 ('Z Bounds', (-1.5, 1.5), '{:.3e}, {:.3e}')]

In [14]:
internal_mesh._get_attrs()[3]

('Y Bounds', (0.009999999776482582, 3.0), '{:.3e}, {:.3e}')

In [15]:
internal_mesh._get_attrs()[3][1][0]

0.009999999776482582

In [16]:
from openfoam.post import get_bbox


get_bbox(internal_mesh)

(-1.5, 1.5, 0.009999999776482582, 3.0, -1.5, 1.5)

In [17]:
internal_mesh

UnstructuredGrid (0x7fc0dad50d00)
  N Cells:    62188
  N Points:   77648
  X Bounds:   -1.500e+00, 1.500e+00
  Y Bounds:   1.000e-02, 3.000e+00
  Z Bounds:   -1.500e+00, 1.500e+00
  N Arrays:   10

In [46]:
from openfoam.post import spatial_sample_case


# b_box = [-1e3, 1e3, 1e-2, 1e3, -1e3, 1e3]
b_box = [-1.5e0, 1.5e0, 1e-2, 3e0, -1.5e0, 1.5e0]

sampled = spatial_sample_case(FILE_PATH, b_box, 0.2)
sampled

StructuredGrid (0x7fc03702eec0)
  N Cells:      2744
  N Points:     3375
  X Bounds:     -1.400e+00, 1.400e+00
  Y Bounds:     0.000e+00, 2.800e+00
  Z Bounds:     -1.400e+00, 1.400e+00
  Dimensions:   15, 15, 15
  N Arrays:     5

In [19]:
sampled["U"].reshape((3, 200, 399, 399))

pyvista_ndarray([[[[0., 0., 0., ..., 0., 0., 0.],
                   [0., 0., 0., ..., 0., 0., 0.],
                   [0., 0., 0., ..., 0., 0., 0.],
                   ...,
                   [0., 0., 0., ..., 0., 0., 0.],
                   [0., 0., 0., ..., 0., 0., 0.],
                   [0., 0., 0., ..., 0., 0., 0.]],

                  [[0., 0., 0., ..., 0., 0., 0.],
                   [0., 0., 0., ..., 0., 0., 0.],
                   [0., 0., 0., ..., 0., 0., 0.],
                   ...,
                   [0., 0., 0., ..., 0., 0., 0.],
                   [0., 0., 0., ..., 0., 0., 0.],
                   [0., 0., 0., ..., 0., 0., 0.]],

                  [[0., 0., 0., ..., 0., 0., 0.],
                   [0., 0., 0., ..., 0., 0., 0.],
                   [0., 0., 0., ..., 0., 0., 0.],
                   ...,
                   [0., 0., 0., ..., 0., 0., 0.],
                   [0., 0., 0., ..., 0., 0., 0.],
                   [0., 0., 0., ..., 0., 0., 0.]],

                  ...,

In [20]:
type(sampled)

pyvista.core.pointset.StructuredGrid

In [21]:
type(sampled)

pyvista.core.pointset.StructuredGrid

In [22]:
print(type(sampled["U"]))
sampled["U"]

<class 'pyvista.core.pyvista_ndarray.pyvista_ndarray'>


pyvista_ndarray([[0., 0., 0.],
                 [0., 0., 0.],
                 [0., 0., 0.],
                 ...,
                 [0., 0., 0.],
                 [0., 0., 0.],
                 [0., 0., 0.]], dtype=float32)

In [23]:
from pyvista import convert_array


converted = convert_array(sampled["U"])
print(type(converted))
print(converted)

<class 'vtkmodules.vtkCommonCore.vtkTypeFloat32Array'>
vtkTypeFloat32Array (0x58dbe60)
  Debug: Off
  Modified Time: 4841
  Reference Count: 1
  Registered Events: (none)
  Name: (none)
  Data type: float
  Size: 95520600
  MaxId: 95520599
  NumberOfComponents: 3
  Information: 0
  Name: (none)
  Number Of Components: 3
  Number Of Tuples: 31840200
  Size: 95520600
  MaxId: 95520599
  LookupTable: (none)




In [24]:
print(type(convert_array(converted)))

<class 'numpy.ndarray'>


In [25]:
type(sampled["U"])

pyvista.core.pyvista_ndarray.pyvista_ndarray

In [26]:
from sklearn.preprocessing import normalize


normalized = normalize(sampled["U"])
print(type(normalized))
print(normalized)

<class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
from openfoam.post import normalize_upk


nu, np, nk = normalize_upk(sampled)
print(nu)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [28]:
normalized = normalize(sampled["p"].reshape(-1,1))
print(type(normalized))
print(normalized)

<class 'numpy.ndarray'>
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [29]:
from openfoam.post import rms

rms_of_sampled(sampled, sampled)

ImportError: cannot import name 'rms' from 'openfoam.post' (/home/ubuntu/cfd/openfoam/post.py)