In [1]:
from pyvista import OpenFOAMReader


# FILE_PATH = "./data/results/windAroundBuildingsOld/open.foam"
FILE_PATH = "./data/results/buildingWindRef/open.foam"


reader = OpenFOAMReader(FILE_PATH)

In [2]:
print(f"All patch names: {reader.patch_array_names}")
print(f"All patch status: {reader.all_patch_arrays_status}")

All patch names: ['internalMesh', 'patch/inlet', 'patch/outlet', 'patch/ground', 'patch/object', 'patch/fixedWalls']
All patch status: {'internalMesh': True, 'patch/inlet': True, 'patch/outlet': True, 'patch/ground': True, 'patch/object': True, 'patch/fixedWalls': True}


In [3]:
mesh = reader.read()
internal_mesh = mesh["internalMesh"]  # or internal_mesh = mesh[0]

2023-06-17 23:32:15.567 (   1.068s) [          162BE3]  vtkOpenFOAMReader.cxx:8654   ERR| vtkOpenFOAMReaderPrivate (0x137cdae90): Error reading line 28 of ./data/results/buildingWindRef/0/U: Expected number, string or ( for uniform entry, found Uinlet
ERROR:root:Error reading line 28 of ./data/results/buildingWindRef/0/U: Expected number, string or ( for uniform entry, found Uinlet
ERROR:root:Error reading line 21 of ./data/results/buildingWindRef/0/epsilon: Expected number, string or ( for uniform entry, found epsilonInlet
2023-06-17 23:32:15.568 (   1.069s) [          162BE3]  vtkOpenFOAMReader.cxx:8654   ERR| vtkOpenFOAMReaderPrivate (0x137cdae90): Error reading line 21 of ./data/results/buildingWindRef/0/epsilon: Expected number, string or ( for uniform entry, found epsilonInlet
ERROR:root:Error reading line 21 of ./data/results/buildingWindRef/0/k: Expected number, string or ( for uniform entry, found kInlet
2023-06-17 23:32:15.569 (   1.070s) [          162BE3]  vtkOpenFOAMReader

In [4]:
print(f"Mesh patches: {mesh.keys()}")

Mesh patches: ['internalMesh', 'boundary']


In [5]:
print(internal_mesh)

UnstructuredGrid (0x111d81c60)
  N Cells:    2075341
  N Points:   2332548
  X Bounds:   -1.000e+03, 1.000e+03
  Y Bounds:   -1.354e+00, 1.000e+03
  Z Bounds:   -1.000e+03, 1.000e+03
  N Arrays:   0


In [6]:
print(internal_mesh.cell_data)
print(internal_mesh.point_data)
print(f"Available Time Values: {reader.time_values}")
reader.set_active_time_value(50)
mesh = reader.read()
internal_mesh = mesh["internalMesh"]

pyvista DataSetAttributes
Association     : CELL
Active Scalars  : None
Active Vectors  : None
Active Texture  : None
Active Normals  : None
Contains arrays : None
pyvista DataSetAttributes
Association     : POINT
Active Scalars  : None
Active Vectors  : None
Active Texture  : None
Active Normals  : None
Contains arrays : None
Available Time Values: [0.0, 50.0]


In [7]:
# mesh.plot()

In [8]:
type(mesh)

pyvista.core.composite.MultiBlock

In [9]:
type(reader.time_values[0])

float

In [10]:
type(reader)

pyvista.utilities.reader.OpenFOAMReader

In [11]:
type(internal_mesh)

pyvista.core.pointset.UnstructuredGrid

In [12]:
internal_mesh._get_attrs()

[('N Cells', 2075341, '{}'),
 ('N Points', 2332548, '{}'),
 ('X Bounds', (-1000.0, 1000.0), '{:.3e}, {:.3e}'),
 ('Y Bounds', (-1.3538024425506592, 1000.0), '{:.3e}, {:.3e}'),
 ('Z Bounds', (-1000.0, 1000.0), '{:.3e}, {:.3e}')]

In [13]:
internal_mesh._get_attrs()[3]

('Y Bounds', (-1.3538024425506592, 1000.0), '{:.3e}, {:.3e}')

In [14]:
internal_mesh._get_attrs()[3][1][0]

-1.3538024425506592

In [15]:
from openfoam.post import get_bbox


get_bbox(internal_mesh)

(-1000.0, 1000.0, -1.3538024425506592, 1000.0, -1000.0, 1000.0)

In [16]:
internal_mesh

UnstructuredGrid (0x17af023e0)
  N Cells:    2075341
  N Points:   2332548
  X Bounds:   -1.000e+03, 1.000e+03
  Y Bounds:   -1.354e+00, 1.000e+03
  Z Bounds:   -1.000e+03, 1.000e+03
  N Arrays:   10

In [17]:
from openfoam.post import spatial_sample


b_box = [-1e3, 1e3, 1e-2, 1e3, -1e3, 1e3]

sampled = spatial_sample(FILE_PATH, b_box, 5)
sampled

StructuredGrid (0x2c13728c0)
  N Cells:      31522396
  N Points:     31840200
  X Bounds:     -9.950e+02, 9.950e+02
  Y Bounds:     0.000e+00, 9.950e+02
  Z Bounds:     -9.950e+02, 9.950e+02
  Dimensions:   200, 399, 399
  N Arrays:     5

In [18]:
sampled["U"].reshape((3, 200, 399, 399))

pyvista_ndarray([[[[0.        , 0.        , 0.        , ...,
                    0.        , 0.        , 0.        ],
                   [0.        , 0.        , 0.        , ...,
                    0.        , 0.        , 0.        ],
                   [0.        , 0.        , 0.        , ...,
                    0.        , 0.        , 0.        ],
                   ...,
                   [0.        , 0.        , 0.        , ...,
                    0.43510443, 0.00666059, 0.27913767],
                   [0.        , 0.        , 0.        , ...,
                    0.        , 0.        , 0.        ],
                   [0.        , 0.        , 0.        , ...,
                    0.        , 0.        , 0.        ]],

                  [[0.        , 0.        , 0.        , ...,
                    0.        , 0.        , 0.        ],
                   [0.        , 0.        , 0.        , ...,
                    0.        , 0.        , 0.        ],
                   [0.        

In [19]:
type(sampled)

pyvista.core.pointset.StructuredGrid

In [20]:
type(sampled)

pyvista.core.pointset.StructuredGrid

In [21]:
print(type(sampled["U"]))
sampled["U"]

<class 'pyvista.core.pyvista_ndarray.pyvista_ndarray'>


pyvista_ndarray([[0., 0., 0.],
                 [0., 0., 0.],
                 [0., 0., 0.],
                 ...,
                 [0., 0., 0.],
                 [0., 0., 0.],
                 [0., 0., 0.]], dtype=float32)

In [22]:
from pyvista import convert_array


converted = convert_array(sampled["U"])
print(type(converted))
print(converted)

<class 'vtkmodules.vtkCommonCore.vtkTypeFloat32Array'>
vtkTypeFloat32Array (0x130672090)
  Debug: Off
  Modified Time: 4805
  Reference Count: 1
  Registered Events: (none)
  Name: (none)
  Data type: float
  Size: 95520600
  MaxId: 95520599
  NumberOfComponents: 3
  Information: 0x0
  Name: (none)
  Number Of Components: 3
  Number Of Tuples: 31840200
  Size: 95520600
  MaxId: 95520599
  LookupTable: (none)




In [23]:
print(type(convert_array(converted)))

<class 'numpy.ndarray'>


In [24]:
type(sampled["U"])

pyvista.core.pyvista_ndarray.pyvista_ndarray

In [25]:
from sklearn.preprocessing import normalize


normalized = normalize(sampled["U"])
print(type(normalized))
print(normalized)

<class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
from openfoam.post import normalize_upk


nu, np, nk = normalize_upk(sampled)
print(nu)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [27]:
normalized = normalize(sampled["p"].reshape(-1,1))
print(type(normalized))
print(normalized)

<class 'numpy.ndarray'>
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [28]:
from openfoam.post import rms

rms_of_sampled(sampled, sampled)

0.0