In [43]:
from pyvista import OpenFOAMReader


FILE_PATH = "/Users/chanwooahn/openfoam/OpenFOAM/openfoam-2212/run/refCaseSolved3/open.foam"
# FILE_PATH = "./testCase/open.foam"

reader = OpenFOAMReader(FILE_PATH)

In [44]:
print(f"All patch names: {reader.patch_array_names}")
print(f"All patch status: {reader.all_patch_arrays_status}")

All patch names: ['internalMesh', 'patch/inlet', 'patch/outlet', 'patch/ground', 'patch/object', 'patch/fixedWalls']
All patch status: {'internalMesh': True, 'patch/inlet': True, 'patch/outlet': True, 'patch/ground': True, 'patch/object': True, 'patch/fixedWalls': True}


In [45]:
mesh = reader.read()
internal_mesh = mesh["internalMesh"]  # or internal_mesh = mesh[0]

ERROR:root:Error reading line 23 of /Users/chanwooahn/openfoam/OpenFOAM/openfoam-2212/run/refCaseSolved3/0/U: Expected number, string or ( for uniform entry, found Uinlet
2023-06-20 19:37:43.927 (1368.369s) [          252D51]  vtkOpenFOAMReader.cxx:8654   ERR| vtkOpenFOAMReaderPrivate (0x287b12b90): Error reading line 23 of /Users/chanwooahn/openfoam/OpenFOAM/openfoam-2212/run/refCaseSolved3/0/U: Expected number, string or ( for uniform entry, found Uinlet
ERROR:root:Error reading line 21 of /Users/chanwooahn/openfoam/OpenFOAM/openfoam-2212/run/refCaseSolved3/0/epsilon: Expected number, string or ( for uniform entry, found epsilonInlet
2023-06-20 19:37:43.929 (1368.371s) [          252D51]  vtkOpenFOAMReader.cxx:8654   ERR| vtkOpenFOAMReaderPrivate (0x287b12b90): Error reading line 21 of /Users/chanwooahn/openfoam/OpenFOAM/openfoam-2212/run/refCaseSolved3/0/epsilon: Expected number, string or ( for uniform entry, found epsilonInlet
ERROR:root:Error reading line 21 of /Users/chanwooahn/

In [46]:
print(f"Mesh patches: {mesh.keys()}")

Mesh patches: ['internalMesh', 'boundary']


In [47]:
print(internal_mesh)

UnstructuredGrid (0x283ed2980)
  N Cells:    1287059
  N Points:   1461370
  X Bounds:   -5.000e+02, 5.000e+02
  Y Bounds:   -4.211e-01, 5.000e+02
  Z Bounds:   -5.000e+02, 5.000e+02
  N Arrays:   0


In [48]:
print(internal_mesh.cell_data)
print(internal_mesh.point_data)
print(f"Available Time Values: {reader.time_values}")
reader.set_active_time_value(reader.time_values[-1])
mesh = reader.read()
internal_mesh = mesh["internalMesh"]

pyvista DataSetAttributes
Association     : CELL
Active Scalars  : None
Active Vectors  : None
Active Texture  : None
Active Normals  : None
Contains arrays : None
pyvista DataSetAttributes
Association     : POINT
Active Scalars  : None
Active Vectors  : None
Active Texture  : None
Active Normals  : None
Contains arrays : None
Available Time Values: [0.0, 41.0]


In [49]:
type(reader)

pyvista.utilities.reader.OpenFOAMReader

In [50]:
type(mesh)

pyvista.core.composite.MultiBlock

In [51]:
type(internal_mesh)

pyvista.core.pointset.UnstructuredGrid

In [52]:
# internal_mesh._get_attrs()

In [53]:
# internal_mesh._get_attrs()[3]

In [54]:
# internal_mesh._get_attrs()[3][1][0]

In [55]:
from openfoam.post import get_bbox

get_bbox(internal_mesh)

(-500.0, 500.0, -0.42114827036857605, 500.0, -500.0, 500.0)

In [56]:
internal_mesh

UnstructuredGrid (0x177037ee0)
  N Cells:    1287059
  N Points:   1461370
  X Bounds:   -5.000e+02, 5.000e+02
  Y Bounds:   -4.211e-01, 5.000e+02
  Z Bounds:   -5.000e+02, 5.000e+02
  N Arrays:   10

In [57]:
from openfoam.post import spatial_sample_case_even


b_box = [-1.5, 1.5, 0, 3, -1.5, 1.5]

sampled = spatial_sample_case_even(FILE_PATH, b_box, 0.185)
sampled

x:  [-1.3875 -1.2025 -1.0175 -0.8325 -0.6475 -0.4625 -0.2775 -0.0925  0.0925
  0.2775  0.4625  0.6475  0.8325  1.0175  1.2025  1.3875]
xs:  [[[-1.3875 -1.3875 -1.3875 ... -1.3875 -1.3875 -1.3875]
  [-1.3875 -1.3875 -1.3875 ... -1.3875 -1.3875 -1.3875]
  [-1.3875 -1.3875 -1.3875 ... -1.3875 -1.3875 -1.3875]
  ...
  [-1.3875 -1.3875 -1.3875 ... -1.3875 -1.3875 -1.3875]
  [-1.3875 -1.3875 -1.3875 ... -1.3875 -1.3875 -1.3875]
  [-1.3875 -1.3875 -1.3875 ... -1.3875 -1.3875 -1.3875]]

 [[-1.2025 -1.2025 -1.2025 ... -1.2025 -1.2025 -1.2025]
  [-1.2025 -1.2025 -1.2025 ... -1.2025 -1.2025 -1.2025]
  [-1.2025 -1.2025 -1.2025 ... -1.2025 -1.2025 -1.2025]
  ...
  [-1.2025 -1.2025 -1.2025 ... -1.2025 -1.2025 -1.2025]
  [-1.2025 -1.2025 -1.2025 ... -1.2025 -1.2025 -1.2025]
  [-1.2025 -1.2025 -1.2025 ... -1.2025 -1.2025 -1.2025]]

 [[-1.0175 -1.0175 -1.0175 ... -1.0175 -1.0175 -1.0175]
  [-1.0175 -1.0175 -1.0175 ... -1.0175 -1.0175 -1.0175]
  [-1.0175 -1.0175 -1.0175 ... -1.0175 -1.0175 -1.0175]
  ..

StructuredGrid (0x2840af9a0)
  N Cells:      3375
  N Points:     4096
  X Bounds:     -1.387e+00, 1.387e+00
  Y Bounds:     9.250e-02, 2.867e+00
  Z Bounds:     -1.387e+00, 1.387e+00
  Dimensions:   16, 16, 16
  N Arrays:     5

In [58]:
sampled["U"].shape

(4096, 3)

In [59]:
type(sampled)

pyvista.core.pointset.StructuredGrid

In [60]:
print(type(sampled["U"]))
sampled["U"]

<class 'pyvista.core.pyvista_ndarray.pyvista_ndarray'>


pyvista_ndarray([[0., 0., 0.],
                 [0., 0., 0.],
                 [0., 0., 0.],
                 ...,
                 [0., 0., 0.],
                 [0., 0., 0.],
                 [0., 0., 0.]], dtype=float32)

In [61]:
from pyvista import convert_array


converted = convert_array(sampled["U"])
print(type(converted))
print(converted)

<class 'vtkmodules.vtkCommonCore.vtkTypeFloat32Array'>
vtkTypeFloat32Array (0x28773ed30)
  Debug: Off
  Modified Time: 9783
  Reference Count: 1
  Registered Events: (none)
  Name: (none)
  Data type: float
  Size: 12288
  MaxId: 12287
  NumberOfComponents: 3
  Information: 0x0
  Name: (none)
  Number Of Components: 3
  Number Of Tuples: 4096
  Size: 12288
  MaxId: 12287
  LookupTable: (none)




In [62]:
print(type(convert_array(converted)))

<class 'numpy.ndarray'>


In [63]:
type(sampled["U"])

pyvista.core.pyvista_ndarray.pyvista_ndarray

In [64]:
# from sklearn.preprocessing import normalize


# normalized = normalize(sampled["U"])
# print(type(normalized))
# print(normalized)

In [65]:
# from openfoam.post import normalize_upk


# nu, np, nk = normalize_upk(sampled)
# print(nu)

In [66]:
# normalized = normalize(sampled["p"].reshape(-1,1))
# print(type(normalized))
# print(normalized)

In [67]:
# from openfoam.post import rms

# rms_of_sampled(sampled, sampled)

In [68]:
# from openfoam.post import spatial_sample_case_even
# import numpy as np

# b_box = [-1.5, 1.5, 0, 3, -1.5, 1.5]

# amp = spatial_sample_case_even(FILE_PATH, b_box, 0.185)
# U = amp["U"]


# print(U.shape)
# U /= U.mean()
# p = amp["p"]
# p /= p.mean()
# k = amp["k"]
# k /= k.mean()
# print(k.shape)


# fs = [U, p, k]
# flats = list(map(lambda x: np.ravel(x), fs))
# flat = np.concatenate(flats)
# flat.shape


In [69]:
# U[:,0].reshape((16, 16, 16)).shape

# u = np.array((3,16,16,16))
# print(u.shape)
# u[0] = U[:,0].reshape((16, 16, 16))
# u[1] = U[:,1].reshape((16, 16, 16))
# u[2] = U[:,2].reshape((16, 16, 16))
# u = u[:].ravel()

In [70]:
dir(sampled)

['ALL_PIECES_EXTENT',
 'AddObserver',
 'AllocateCellGhostArray',
 'AllocatePointGhostArray',
 'AttributeTypes',
 'BOUNDING_BOX',
 'BlankCell',
 'BlankPoint',
 'BreakOnError',
 'BuildCellLocator',
 'BuildLocator',
 'BuildPointLocator',
 'CELL',
 'CELL_DATA_FIELD',
 'CELL_DATA_VECTOR',
 'CheckAttributes',
 'ComputeBounds',
 'CopyAttributes',
 'CopyInformationFromPipeline',
 'CopyInformationToPipeline',
 'CopyStructure',
 'Crop',
 'DATA_EXTENT',
 'DATA_EXTENT_TYPE',
 'DATA_NUMBER_OF_GHOST_LEVELS',
 'DATA_NUMBER_OF_PIECES',
 'DATA_OBJECT',
 'DATA_OBJECT_FIELD',
 'DATA_PIECE_NUMBER',
 'DATA_TIME_STEP',
 'DATA_TYPE_NAME',
 'DIRECTION',
 'DataHasBeenGenerated',
 'DebugOff',
 'DebugOn',
 'DeepCopy',
 'EDGE',
 'EDGE_DATA_VECTOR',
 'EditableOff',
 'EditableOn',
 'ExtendedNew',
 'FIELD',
 'FIELD_ACTIVE_ATTRIBUTE',
 'FIELD_ARRAY_TYPE',
 'FIELD_ASSOCIATION',
 'FIELD_ASSOCIATION_CELLS',
 'FIELD_ASSOCIATION_EDGES',
 'FIELD_ASSOCIATION_NONE',
 'FIELD_ASSOCIATION_POINTS',
 'FIELD_ASSOCIATION_POINTS_THE

In [71]:
sampled.points_matrix

pyvista_ndarray([[[[-1.3875,  0.0925, -1.3875],
                   [-1.3875,  0.0925, -1.2025],
                   [-1.3875,  0.0925, -1.0175],
                   ...,
                   [-1.3875,  0.0925,  1.0175],
                   [-1.3875,  0.0925,  1.2025],
                   [-1.3875,  0.0925,  1.3875]],

                  [[-1.3875,  0.2775, -1.3875],
                   [-1.3875,  0.2775, -1.2025],
                   [-1.3875,  0.2775, -1.0175],
                   ...,
                   [-1.3875,  0.2775,  1.0175],
                   [-1.3875,  0.2775,  1.2025],
                   [-1.3875,  0.2775,  1.3875]],

                  [[-1.3875,  0.4625, -1.3875],
                   [-1.3875,  0.4625, -1.2025],
                   [-1.3875,  0.4625, -1.0175],
                   ...,
                   [-1.3875,  0.4625,  1.0175],
                   [-1.3875,  0.4625,  1.2025],
                   [-1.3875,  0.4625,  1.3875]],

                  ...,

                  [[-1.3875,  2.49

In [72]:
print(sampled.points_matrix.shape)
print(sampled["U"].shape)
print(sampled["p"].shape)

(16, 16, 16, 3)
(4096, 3)
(4096,)


In [73]:
# from numpy import arange, concatenate, meshgrid
# from pyvista import StructuredGrid
# from openfoam.mesh import BoundingBox
# from openfoam.post import read_case_last


# def grid_from_bbox_even(b_box: BoundingBox, grid_size: float) -> StructuredGrid:
#     xn = list(reversed(arange(-grid_size/2, b_box[0], -grid_size)))
#     xp = arange(grid_size/2, b_box[1], grid_size)
#     x = concatenate([xn, xp])

#     yn = list(reversed(arange(-grid_size/2, b_box[2], -grid_size)))
#     yp = arange(grid_size/2, b_box[3], grid_size)
#     y = concatenate([yn, yp])

#     zn = list(reversed(arange(-grid_size/2, b_box[4], -grid_size)))
#     zp = arange(grid_size/2, b_box[5], grid_size)
#     z = concatenate([zn, zp])
#     print("x: ", x)

#     xs, ys, zs = meshgrid(x, y, z, indexing='ij')
#     print("xs: ", xs)

#     return StructuredGrid(xs, ys, zs)

# def spatial_sample_case_even(path: str, b_box: BoundingBox, grid_size: float) -> StructuredGrid:
#     meshes = read_case_last(path)
#     internal_mesh = meshes["internalMesh"]
    
#     grid = grid_from_bbox_even(b_box, grid_size)
#     sampled = grid.interpolate(internal_mesh)

#     return sampled

# b_box = [-10, 10, -10, 10, -10, 10,]

# grid_from_bbox_even(b_box, 2)

In [74]:
# from numpy import float32, arange, meshgrid


# xrng = arange(-10, 10, 2, dtype=float32)
# yrng = arange(-10, 10, 5, dtype=float32)
# zrng = arange(-10, 10, 1, dtype=float32)
# print("xrng: ", xrng)

# x, y, z = meshgrid(xrng, yrng, zrng, indexing='ij')
# print("x: ", x)

# grid = StructuredGrid(x, y, z)

In [75]:
from more_itertools import flatten, consume
from numpy import array
import numpy as np

# pm = sampled.points_matrix

# ps_shape = (4096, 3)

# ps = pm.reshape(ps_shape)
# us = sampled["U"]

# print(ps[0][0])


# u_field = np.empty((256, 128, 256))

# def set_u(x, y, z, v):
#     u_field[x][y][z] = v

# consume(map(lambda p: set_u(p[0][0], p[0][1], p[0][2], p[1]), zip(ps, us)))

# u_field


In [76]:
from numpy import ndarray
import numpy as np


x = np.array([0, 0])

def set_x(i, v):
    x[i] = v

set_x(1, 3)

x


array([0, 3])