In [8]:
from pyvista import OpenFOAMReader


# FILE_PATH = "./data/results/windAroundBuildingsOld/open.foam"
FILE_PATH = "./testCase/open.foam"


reader = OpenFOAMReader(FILE_PATH)

In [28]:
from openfoam.post import spatial_sample
import numpy as np

b_box = [-1.5, 1.5, 0, 3, -1.5, 1.5]

amp = spatial_sample_(FILE_PATH, b_box, 0.185)
U = amp["U"]


print(U.shape)
U /= U.mean()
p = amp["p"]
p /= p.mean()
k = amp["k"]
k /= k.mean()
print(k.shape)


fs = [U, p, k]
flats = list(map(lambda x: np.ravel(x), fs))
flat = np.concatenate(flats)
flat.shape



(4096, 3)
(4096,)


(20480,)

In [29]:
U.shape

(4096, 3)

In [35]:
U[:,0].reshape((16, 16, 16)).shape

u = np.array((3,16,16,16))
print(u.shape)
u[0] = U[:,0].reshape((16, 16, 16))
u[1] = U[:,1].reshape((16, 16, 16))
u[2] = U[:,2].reshape((16, 16, 16))
u = u[:].ravel()

ValueError: setting an array element with a sequence.

In [10]:
print(f"All patch names: {reader.patch_array_names}")
print(f"All patch status: {reader.all_patch_arrays_status}")

All patch names: ['internalMesh', 'patch/inlet', 'patch/outlet', 'patch/ground', 'patch/object', 'patch/fixedWalls']
All patch status: {'internalMesh': True, 'patch/inlet': True, 'patch/outlet': True, 'patch/ground': True, 'patch/object': True, 'patch/fixedWalls': True}


In [11]:
mesh = reader.read()
internal_mesh = mesh["internalMesh"]  # or internal_mesh = mesh[0]

ERROR:root:Error reading line 28 of ./testCase/0/U: Expected number, string or ( for uniform entry, found Uinlet
ERROR:root:Error reading line 21 of ./testCase/0/epsilon: Expected number, string or ( for uniform entry, found epsilonInlet
ERROR:root:Error reading line 21 of ./testCase/0/k: Expected number, string or ( for uniform entry, found kInlet
ERROR:root:Error reading line 70 of ./testCase/0/nut: Unsupported directive includeEtc
ERROR:root:Error reading line 66 of ./testCase/0/p: Unsupported directive includeEtc


In [12]:
print(f"Mesh patches: {mesh.keys()}")

Mesh patches: ['internalMesh', 'boundary']


In [13]:
print(internal_mesh)

UnstructuredGrid (0x20936947640)
  N Cells:    62188
  N Points:   77648
  X Bounds:   -1.500e+00, 1.500e+00
  Y Bounds:   1.000e-02, 3.000e+00
  Z Bounds:   -1.500e+00, 1.500e+00
  N Arrays:   0


In [14]:
print(internal_mesh.cell_data)
print(internal_mesh.point_data)
print(f"Available Time Values: {reader.time_values}")
reader.set_active_time_value(73)
mesh = reader.read()
internal_mesh = mesh["internalMesh"]

pyvista DataSetAttributes
Association     : CELL
Active Scalars  : None
Active Vectors  : None
Active Texture  : None
Active Normals  : None
Contains arrays : None
pyvista DataSetAttributes
Association     : POINT
Active Scalars  : None
Active Vectors  : None
Active Texture  : None
Active Normals  : None
Contains arrays : None
Available Time Values: [0.0, 50.0, 73.0]


In [15]:
# mesh.plot()

In [16]:
type(mesh)

pyvista.core.composite.MultiBlock

In [17]:
type(reader.time_values[0])

float

In [18]:
type(reader)

pyvista.utilities.reader.OpenFOAMReader

In [19]:
type(internal_mesh)

pyvista.core.pointset.UnstructuredGrid

In [20]:
internal_mesh._get_attrs()

[('N Cells', 62188, '{}'),
 ('N Points', 77648, '{}'),
 ('X Bounds', (-1.5, 1.5), '{:.3e}, {:.3e}'),
 ('Y Bounds', (0.009999999776482582, 3.0), '{:.3e}, {:.3e}'),
 ('Z Bounds', (-1.5, 1.5), '{:.3e}, {:.3e}')]

In [21]:
internal_mesh._get_attrs()[3]

('Y Bounds', (0.009999999776482582, 3.0), '{:.3e}, {:.3e}')

In [22]:
internal_mesh._get_attrs()[3][1][0]

0.009999999776482582

In [23]:
from openfoam.post import get_bbox


get_bbox(internal_mesh)

(-1.5, 1.5, 0.009999999776482582, 3.0, -1.5, 1.5)

In [24]:
internal_mesh

UnstructuredGrid (0x20968d06f80)
  N Cells:    62188
  N Points:   77648
  X Bounds:   -1.500e+00, 1.500e+00
  Y Bounds:   1.000e-02, 3.000e+00
  Z Bounds:   -1.500e+00, 1.500e+00
  N Arrays:   10

In [25]:
from openfoam.post import spatial_sample_


b_box = [-1.5, 1.5, 0, 3, -1.5, 1.5]

sampled = spatial_sample_(FILE_PATH, b_box, 0.185)
sampled

StructuredGrid (0x209693514e0)
  N Cells:      3375
  N Points:     4096
  X Bounds:     -1.387e+00, 1.387e+00
  Y Bounds:     9.250e-02, 2.867e+00
  Z Bounds:     -1.387e+00, 1.387e+00
  Dimensions:   16, 16, 16
  N Arrays:     5

In [26]:
sampled["U"].reshape((3, 15, 15, 15))

ValueError: cannot reshape array of size 12288 into shape (3,15,15,15)

In [ ]:
type(sampled)

pyvista.core.pointset.StructuredGrid

In [ ]:
type(sampled)

pyvista.core.pointset.StructuredGrid

In [ ]:
print(type(sampled["U"]))
sampled["U"]

<class 'pyvista.core.pyvista_ndarray.pyvista_ndarray'>


pyvista_ndarray([[ 2.2390141 , -0.50837547, -1.222868  ],
                 [ 2.2599409 , -0.57924896, -1.2229254 ],
                 [ 2.2949314 , -0.65328676, -1.2153988 ],
                 ...,
                 [ 6.101565  , -0.63350886, -0.10682932],
                 [ 5.396949  , -0.44429392, -0.06287695],
                 [ 4.805408  , -0.2977851 , -0.03961771]], dtype=float32)

In [ ]:
from pyvista import convert_array


converted = convert_array(sampled["U"])
print(type(converted))
print(converted)

<class 'vtkmodules.vtkCommonCore.vtkTypeFloat32Array'>
vtkTypeFloat32Array (000001EE0D70B070)
  Debug: Off
  Modified Time: 7526
  Reference Count: 1
  Registered Events: (none)
  Name: (none)
  Data type: float
  Size: 10125
  MaxId: 10124
  NumberOfComponents: 3
  Information: 0000000000000000
  Name: (none)
  Number Of Components: 3
  Number Of Tuples: 3375
  Size: 10125
  MaxId: 10124
  LookupTable: (none)




In [ ]:
print(type(convert_array(converted)))

<class 'numpy.ndarray'>


In [ ]:
type(sampled["U"])

pyvista.core.pyvista_ndarray.pyvista_ndarray

In [ ]:
from sklearn.preprocessing import normalize


normalized = normalize(sampled["U"])
print(type(normalized))
print(normalized)

<class 'numpy.ndarray'>
[[ 0.8607115  -0.19542736 -0.47008926]
 [ 0.8579602  -0.21990512 -0.46426937]
 [ 0.85701674 -0.2439627  -0.4538772 ]
 ...
 [ 0.9945023  -0.10325646 -0.01741226]
 [ 0.9965614  -0.08204009 -0.0116104 ]
 [ 0.99805164 -0.06184801 -0.00822834]]


In [ ]:
from openfoam.post import normalize_upk


nu, np, nk = normalize_upk(sampled)
print(nu)

[[ 1.]
 [-1.]
 [-1.]
 ...
 [ 1.]
 [-1.]
 [-1.]]


In [ ]:
normalized = normalize(sampled["p"].reshape(-1,1))
print(type(normalized))
print(normalized)

<class 'numpy.ndarray'>
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]


In [ ]:
from openfoam.post import rms

rms_of_sampled(sampled, sampled)

ImportError: cannot import name 'rms' from 'openfoam.post' (c:\Users\pale\repos\pygan\openfoam\post.py)